language: node_js

node_js:
  - "6.9.4"
  - "5"
  - "4"
  - "0.12"
  - "0.10"

before_install:
  - node --version
  - npm --version

install:
  - npm install
  - npm install cucumber@~1.3.3

notifications:
  email:
    - simon@simondean.org
